import { StyleSheet } from '@react-pdf/renderer'

export const colors = {
  text: '#0F172A',
  muted: '#64748B',
  accent: '#10B981',
  accentSoft: '#E6FAF3',
  border: '#E2E8F0',
}

export const styles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 40,
    fontSize: 9,
    color: colors.text,
    fontFamily: 'Helvetica',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  logo: {
    width: 64,
    height: 64,
    objectFit: 'contain',
  },
  invoiceNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    color: colors.text,
    flex: 1,
  },
  parties: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  partyBlock: {
    flex: 1,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 6,
  },
  partyTitle: {
    fontSize: 8,
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
    fontWeight: 'bold',
  },
  partyLine: {
    marginBottom: 2,
    lineHeight: 1.4,
  },
  meta: {
    marginBottom: 16,
    lineHeight: 1.6,
  },
  metaLabel: {
    color: colors.muted,
  },
  table: {
    marginBottom: 16,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: colors.accentSoft,
    padding: 8,
    borderRadius: 4,
    fontWeight: 'bold',
    fontSize: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    color: colors.text,
  },
  tableRow: {
    flexDirection: 'row',
    padding: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  colRef: { width: '24%', paddingRight: 4 },
  colDesc: { width: '36%', paddingRight: 4 },
  colPrice: { width: '13%', textAlign: 'right' },
  colQty: { width: '10%', textAlign: 'right' },
  colTotal: { width: '17%', textAlign: 'right' },
  totalsBlock: {
    alignSelf: 'flex-end',
    width: '40%',
    marginTop: 8,
  },
  totalsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  totalsRowFinal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: colors.text,
    fontWeight: 'bold',
    fontSize: 11,
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 8,
    color: colors.muted,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
})
