import { supabase } from '@/lib/supabase'
import type {
  Invoice,
  InvoiceLine,
  InvoiceInsert,
  InvoiceUpdate,
  InvoiceLineInsert,
  Client,
} from '@/types/database'

export interface InvoiceFilters {
  clientId?: string
  month?: string
  statuses?: ('pending' | 'paid' | 'late')[]
}

export async function listInvoices(filters?: InvoiceFilters): Promise<Invoice[]> {
  let q = supabase
    .from('invoices')
    .select('*')
    .is('archived_at', null)
    .order('created_at', { ascending: false })

  if (filters?.clientId) {
    q = q.eq('client_id', filters.clientId)
  }
  if (filters?.month) {
    const [y, m] = filters.month.split('-')
    const yi = parseInt(y, 10)
    const mi = parseInt(m, 10)
    // Compute next month's first day in pure date arithmetic to avoid timezone drift
    // (toISOString on a local-midnight Date in CEST returns the previous calendar day).
    const ny = mi === 12 ? yi + 1 : yi
    const nm = mi === 12 ? 1 : mi + 1
    const start = `${y}-${m}-01`
    const end = `${ny}-${String(nm).padStart(2, '0')}-01`
    q = q.gte('invoice_date', start).lt('invoice_date', end)
  }
  const { data, error } = await q
  if (error) throw error
  return data ?? []
}

export async function getInvoiceWithLines(
  id: string
): Promise<{ invoice: Invoice; lines: InvoiceLine[]; client: Client }> {
  const { data: invoice, error: invErr } = await supabase
    .from('invoices')
    .select('*')
    .eq('id', id)
    .single()
  if (invErr) throw invErr
  const { data: lines, error: lineErr } = await supabase
    .from('invoice_lines')
    .select('*')
    .eq('invoice_id', id)
    .order('position', { ascending: true })
  if (lineErr) throw lineErr
  const { data: client, error: clientErr } = await supabase
    .from('clients')
    .select('*')
    .eq('id', invoice.client_id)
    .single()
  if (clientErr) throw clientErr
  return { invoice, lines: lines ?? [], client }
}

export async function createInvoice(
  input: Omit<InvoiceInsert, 'user_id'>,
  lines: Omit<InvoiceLineInsert, 'invoice_id'>[],
  importedPdf?: File | null
): Promise<Invoice> {
  const { data: userData } = await supabase.auth.getUser()
  const user = userData.user
  if (!user) throw new Error('Non authentifié')

  // Imported PDF: upload to Storage FIRST so we can attach its path to the
  // invoice row. Path is stable per (user, invoice) — we generate the
  // invoice UUID client-side so the file and the DB row reference the same id.
  let importedPath: string | null = null
  let uploadedPathToCleanup: string | null = null
  let preassignedId: string | undefined

  if (importedPdf) {
    preassignedId = crypto.randomUUID()
    importedPath = `${user.id}/${preassignedId}.pdf`
    const { error: upErr } = await supabase.storage
      .from('imported-invoices')
      .upload(importedPath, importedPdf, {
        contentType: 'application/pdf',
        upsert: false,
      })
    if (upErr) throw upErr
    uploadedPathToCleanup = importedPath
  }

  // Supabase types invoices.Insert.id as `never` (auto-generated by the DB).
  // For imported PDFs we pre-assign the UUID to use as the Storage object key,
  // then insert with that id. The escape-hatch cast (`as never`) bypasses
  // Supabase's RejectExcessProperties check — the DB still accepts the explicit id.
  const insertPayload = {
    ...input,
    user_id: user.id,
    imported_pdf_path: importedPath,
    ...(preassignedId ? { id: preassignedId } : {}),
  }
  const { data: invoice, error: invErr } = await supabase
    .from('invoices')
    .insert(insertPayload as never)
    .select('*')
    .single()

  if (invErr) {
    if (uploadedPathToCleanup) {
      await supabase.storage
        .from('imported-invoices')
        .remove([uploadedPathToCleanup])
        .catch((rollbackErr) =>
          console.error('[invoices] storage rollback after failed insert', {
            path: uploadedPathToCleanup,
            rollbackErr,
          })
        )
    }
    throw invErr
  }

  if (lines.length > 0) {
    const linesToInsert: InvoiceLineInsert[] = lines.map((l) => ({
      ...l,
      invoice_id: invoice.id,
    }))
    const { error: lineErr } = await supabase.from('invoice_lines').insert(linesToInsert)
    if (lineErr) {
      // Roll back the invoice (which cascades-removes any partial lines) AND
      // the Storage object if it was uploaded.
      await supabase.from('invoices').delete().eq('id', invoice.id)
      if (uploadedPathToCleanup) {
        await supabase.storage
          .from('imported-invoices')
          .remove([uploadedPathToCleanup])
          .catch(() => {
            /* orphaned file; not fatal */
          })
      }
      throw lineErr
    }
  }

  return invoice
}

export async function getImportedPdfSignedUrl(storagePath: string): Promise<string> {
  const { data, error } = await supabase.storage
    .from('imported-invoices')
    .createSignedUrl(storagePath, 3600)
  if (error) throw error
  return data.signedUrl
}

export async function updateInvoice(
  id: string,
  patch: InvoiceUpdate,
  lines: Omit<InvoiceLineInsert, 'invoice_id'>[]
): Promise<Invoice> {
  if (
    patch.client_id == null ||
    patch.invoice_date == null ||
    patch.payment_method == null ||
    patch.total_ht == null
  ) {
    throw new Error('Champs requis manquants pour la mise à jour')
  }

  const { data, error } = await supabase.rpc('update_invoice_with_lines', {
    p_invoice_id: id,
    p_client_id: patch.client_id,
    p_invoice_date: patch.invoice_date,
    p_due_date: patch.due_date ?? null,
    p_payment_method: patch.payment_method,
    p_total_ht: patch.total_ht,
    p_vat_mention: patch.vat_mention ?? null,
    p_lines: lines,
  })
  if (error) throw error
  return data as Invoice
}

export async function markPaid(id: string, paidAt: string): Promise<void> {
  const { error } = await supabase
    .from('invoices')
    .update({ status: 'paid', paid_at: paidAt })
    .eq('id', id)
  if (error) throw error
}

export async function setPaidAt(id: string, paidAt: string): Promise<void> {
  const { error } = await supabase
    .from('invoices')
    .update({ paid_at: paidAt })
    .eq('id', id)
  if (error) throw error
}

export async function markUnpaid(id: string): Promise<void> {
  const { error } = await supabase
    .from('invoices')
    .update({ status: 'pending', paid_at: null })
    .eq('id', id)
  if (error) throw error
}

export async function archiveInvoice(id: string): Promise<void> {
  const { error } = await supabase
    .from('invoices')
    .update({ archived_at: new Date().toISOString() })
    .eq('id', id)
  if (error) throw error
}
